### ISSUE TITLE
BuyItem Bug

### ISSUE THREAD

**Issue by AgentSlim** [gapadana/esx_supermarket#1]
`Error running system event handling function for resource esx_supermarket: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_supermarket/server/main.lua:70: attempt to call a nil value (field 'Round')
stack traceback:
        @esx_supermarket/server/main.lua:70: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>`

This error message appears when I want to buy an item

**Comment by Trickyyy** [comment]
same
